apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
data:
  application.properties: |-
    topics.inputtopic=topic1
    topics.usertopic=topic2
    topics.staticstopic=topic3